# Based on a combination of:
# https://github.com/jlelong/vscode-latex-basics/blob/635fd947703fda933335f315c2af8723ac156186/languages/markdown-latex-combined-language-configuration.json
# https://github.com/jlelong/vscode-latex-basics/blob/635fd947703fda933335f315c2af8723ac156186/languages/latex-language-configuration.json

comments:
  lineComment: '%'
  blockComment: ['<!--', '-->']
brackets:
  - ['{', '}']
  - ['[', ']']
  - ['(', ')']
  - ['[', ')']
  - ['(', ']']
  - ['\{', '\}']
  - ['\left(', '\right)']
  - ['\left(', '\right.']
  - ['\left.', '\right)']
  - ['\left[', '\right]']
  - ['\left[', '\right.']
  - ['\left.', '\right]']
  - ['\left\{', '\right\}']
  - ['\left\{', '\right.']
  - ['\left.', '\right\}']
  - ['\left<', '\right>']
  - ['\bigl(', '\bigr)']
  - ['\bigl[', '\bigr]']
  - ['\bigl\{', '\bigr\}']
  - ['\Bigl(', '\Bigr)']
  - ['\Bigl[', '\Bigr]']
  - ['\Bigl\{', '\Bigr\}']
  - ['\biggl(', '\biggr)']
  - ['\biggl[', '\biggr]']
  - ['\biggl\{', '\biggr\}']
  - ['\Biggl(', '\Biggr)']
  - ['\Biggl[', '\Biggr]']
  - ['\Biggl\{', '\Biggr\}']
  - ['\langle', '\rangle']
  - ['\lvert', '\rvert']
  - ['\lVert', '\rVert']
  - ['\left|', '\right|']
  - ['\left.', '\right|']
  - ['\left|', '\right.']
  - ['\left\vert', '\right\vert']
  - ['\left\|', '\right\|']
  - ['\left\Vert', '\right\Vert']
  - ['\left\langle', '\right\rangle']
  - ['\left\lvert', '\right\rvert']
  - ['\left\lVert', '\right\rVert']
  - ['\bigl\langle', '\bigr\rangle']
  - ['\bigl|', '\bigr|']
  - ['\bigl\vert', '\bigr\vert']
  - ['\bigl\lvert', '\bigr\rvert']
  - ['\bigl\|', '\bigr\|']
  - ['\bigl\lVert', '\bigr\rVert']
  - ['\bigl\Vert', '\bigr\Vert']
  - ['\Bigl\langle', '\Bigr\rangle']
  - ['\Bigl|', '\Bigr|']
  - ['\Bigl\lvert', '\Bigr\rvert']
  - ['\Bigl\vert', '\Bigr\vert']
  - ['\Bigl\|', '\Bigr\|']
  - ['\Bigl\lVert', '\Bigr\rVert']
  - ['\Bigl\Vert', '\Bigr\Vert']
  - ['\biggl\langle', '\biggr\rangle']
  - ['\biggl|', '\biggr|']
  - ['\biggl\lvert', '\biggr\rvert']
  - ['\biggl\vert', '\biggr\vert']
  - ['\biggl\|', '\biggr\|']
  - ['\biggl\lVert', '\biggr\rVert']
  - ['\biggl\Vert', '\biggr\Vert']
  - ['\Biggl\langle', '\Biggr\rangle']
  - ['\Biggl|', '\Biggr|']
  - ['\Biggl\lvert', '\Biggr\rvert']
  - ['\Biggl\vert', '\Biggr\vert']
  - ['\Biggl\|', '\Biggr\|']
  - ['\Biggl\lVert', '\Biggr\rVert']
  - ['\Biggl\Vert', '\Biggr\Vert']
autoClosingPairs:
  - ['\left(', '\right)']
  - ['\left[', '\right]']
  - ['\left\{', '\right\}']
  - ['\bigl(', '\bigr)']
  - ['\bigl[', '\bigr]']
  - ['\bigl\{', '\bigr\}']
  - ['\Bigl(', '\Bigr)']
  - ['\Bigl[', '\Bigr]']
  - ['\Bigl\{', '\Bigr\}']
  - ['\biggl(', '\biggr)']
  - ['\biggl[', '\biggr]']
  - ['\biggl\{', '\biggr\}']
  - ['\Biggl(', '\Biggr)']
  - ['\Biggl[', '\Biggr]']
  - ['\Biggl\{', '\Biggr\}']
  - ['\(', '\)']
  - ['\[', '\]']
  - ['\{', '\}']
  - ['@(', '']
  - ['@[', '']
  - ['@{', '']
  - ['{', '}']
  - ['[', ']']
  - ['(', ')']
  - ['`', "`"]
surroundingPairs:
  - ['{', '}']
  - ['[', ']']
  - ['(', ')']
  - ['"', '"']
  - ["'", "'"]
  - ['$', '$']
  - ['`', "`"]
  #- ['_', '_']
  - ['*', '*']
indentationRules:
  # Indent after `\command:`, `: env`, `::special`, and `\begin{foo}`
  increaseIndentPattern:
    '\\([a-zA-Z@]+|.):\s*$|^\s*:\s|^\s*::\s*[a-z]+\s*$|^\s*::\s*[a-z].*:\s*$|\\begin{(?!document)([^}]*)}(?!.*\\end{\1})'
  # Decrease indent with `\end{foo}`
  decreaseIndentPattern: '^\s*\\end{(?!document)'
folding:
  markers:
    start: '^\s*%?\s*(region|\\begingroup)\b'
    end: '^\s*%?\s*(endregion|\\endgroup)\b'
autoCloseBefore: ";:.,={}])>\\` \n\t$"
wordPattern:
  pattern: '([*_]{1,})?(\p{Alphabetic}|\p{Number}|\p{Nonspacing_Mark})(((\p{Alphabetic}|\p{Number}|\p{Nonspacing_Mark})|[_])?(\p{Alphabetic}|\p{Number}|\p{Nonspacing_Mark}))*\1'
  flags: 'u'
