name: Tests

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: |
          npm install -g corepack@latest
          corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22
      - name: Install Dependencies
        run: |
          pnpm install
      - name: Run tests
        run: |
          pnpm test
